### ISSUE TITLE
Error: Error Domain=OSSystemExtensionErrorDomain Code=10 "(null)"

### ISSUE THREAD

**Issue by tejomaygadgil** [secretkeysio/GCAdapterDriver#10]
Getting this error when I toggle GCAdapter on: 

```
Failed to activate extension!

Error: Error Domain=OSSystemExtensionErrorDomain Code=10 "(null)"

Details: The operation couldn’t be completed. (OSSystemExtensionErrorDomain error 10.)
```

I'm running it on a MacBook Pro (13-inch, M1, 2020) running MacOS Monterey.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/10650758/175663517-18f5dacf-b3a8-43a4-b4e9-fd7977123c29.png">

**Comment by ryanmcgrath** [comment]
`Code 10` indicates your system isn't allowed to install extensions like this. Are you on a managed device (work, school, parents)...?

**Comment by tejomaygadgil** [comment]
Yeah ;(

Any workarounds?

**Comment by ryanmcgrath** [comment]
Unfortunately no - the driver can't really work around that restriction. :(

If you're looking to play on Dolphin and your adapter supports "PC Mode" (via a hardware switch), you can set it up under "Standard Controller" and use it that way since it doesn't require a driver. Not all adapters support this though (Mayflash, for instance, does).
