### ISSUE TITLE
Install via brew?

### ISSUE THREAD

**Issue by dronenb** [secretkeysio/GCAdapterDriver#22]
Hi @ryanmcgrath,

Thank you for developing this useful utility. Would you be willing to create a `brew tap` repository for this application? I would be happy to contribute the necessary cask code, so long as you can create a repo to store it in as per [this guide](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#creating-a-tap).

Thanks for your consideration.
Ben

**Comment by ryanmcgrath** [comment]
I would prefer not to. It's technically not as clear as one would hope - DriverKit extensions aren't actually removed until something's trashed _and then the machine is rebooted_, so it's not entirely clear that Homebrew (or other) package management would/could cleanly manage that aspect. I also just don't use Homebrew these days (MacPorts instead) so it's not in a path that'd even overlap with my usual development cycle.

In general, I also just find shipping software that's more aimed at end-users via channels like that to be problematic. Brew/apt/etc solve a problem for the technically inclined, but they wind up more often than not just causing support headaches from a maintainer perspective. This repository doesn't get too many of these issues but I do wind up debugging them *very* often elsewhere , and since I'm the only one who does it, I'd really prefer there not be multiple possible paths that someone got a driver onto their machine.

**Comment by dronenb** [comment]
@ryanmcgrath thanks for the explanation and the quick response. I will close out this issue.
